export const config = {
  env: "prod",
  LOCAL_API_URL: "localhost:3000",
  API_URL: "odp-rarity.vercel.app",
  COLLECTION_NAME: "oddaliensnft",
  COLLECTION_TITLE: "OddAliens",
  COLLECTION_DESCRIPTION: 'OddAliens is a collection of unique NFTs with over 140 hand illustrated trait generated by algorithm lives on matic network as ERC-721 NFTs.',
  COLLECTION_IMG_LINK: "https://lh3.googleusercontent.com/seDnwl6haPZ70-cV0msCzyhjTWX_qS5o400qk8PdacbDXqumEGnlw9IMn1S8Q3HBZeisPsFPIkX4nvk9MpSAD7Pouo5yLNA7KOAc=s130",
};
